version: '3'
services:
  aiseg2-influxdb-forwarder:
    container_name: aiseg2-influxdb-forwarder
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
